version: "2"

plugins:
  eslint:
    enabled: true
    config:
      extensions:
        - .js
        - .jsx
  csslint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - test_*
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python

exclude_patterns:
- "**/node_modules/"
- "**/scripts/"
- "**/hooks/"
- "**/secrets/"
- "**/spec/"
- "**/tests/"
- "**/test_*/"
- "**/__pycache__/"
- "**/migrations/"
- "**/env/"
- "**/venv/"
- "**/.*"
- "wsgi.py"
- "settings.py"
- "runner.py"
- "schema.py"
- "manage.py"
- "db.sqlite3"
