version: "2"

plugins:
  # CodeClimate can't find pylint and I don't know why, maybe it's outdated
  pylint:
    enabled: true
    channel: beta 
    config: unbrake-api/.pylintrc
  sonar-python:
    enabled: true
  eslint:
    enabled: true
    config: unbrake-frontend/.eslintrc.json
  markdownlint:
    enabled: true
    checks:
      # Ordered list item prefix
      MD029:
        enabled: false
  # Fixed relevant ones, but most of errors is about POSIX
  # which doesn't matter since environment is dockerized
  # shellcheck:
  #   enabled: true
  pep8:
    enabled: true
  nodesecurity:
    enabled: true
  radon:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python

exclude_patterns:
  - "**/node_modules/"
  - "**/hooks/"
  - "**/secrets/"
  - "**/spec/"
  - "**/tests/"
  - "**/test_*/"
  - "**/__pycache__/"
  - "**/migrations/"
  - "**/env/"
  - "**/.env/"
  - "**/venv/"
  - "**/.venv/"
  - "**/.*rc"
  - unbrake-api/schema.py
  - unbrake-api/manage.py
  - unbrake-api/db.sqlite3
  - unbrake-api/unbrake_api/wsgi.py
  - unbrake-api/unbrake_api/settings.py
  - unbrake-api/unbrake_api/runner.py
