version: "2"

plugins:
  eslint:
    enabled: true
    config:
      extensions:
        - .js
        - .jsx
  csslint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - test_*
  nodesecurity:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python

exclude_patterns:
  - "**/node_modules/"
  - "**/hooks/"
  - "**/secrets/"
  - "**/spec/"
  - "**/tests/"
  - "**/test_*/"
  - "**/__pycache__/"
  - "**/migrations/"
  - "**/env/"
  - "**/.env/"
  - "**/venv/"
  - "**/.venv/"
  - "**/.*rc"
  - unbrake-api/schema.py
  - unbrake-api/manage.py
  - unbrake-api/db.sqlite3
  - unbrake-api/unbrake_api/wsgi.py
  - unbrake-api/unbrake_api/settings.py
  - unbrake-api/unbrake_api/runner.py
