# docker-compose for development

version: '3.7'

services:
  frontend:
    container_name: 'unbrake-frontend-development'
    image: 'unbrake/frontend:latest-development'
    build:
      context: ./unbrake-frontend
      dockerfile: Dockerfile
    volumes:
      - "./unbrake-frontend/src:/app/frontend/src"
      - "./unbrake-frontend/scripts:/app/frontend/scripts"
      - "./.git:/app/.git" # Needed for git hooks
    ports:
      - "3000:3000"

  api:
    container_name: 'unbrake-api-development'
    image: 'unbrake/api:latest-development'
    build:
      context: ./unbrake-api
      dockerfile: Dockerfile
    volumes:
      - "./unbrake-api:/app/api"
      - "./.git:/app/.git" # Needed for git hooks
    ports:
      - "8080:8080"
    secrets:
      - api-django-secret-key
      - mqtt-reading-key
      - mqtt-writing-key

  codeclimate:
    container_name: 'codeclimate'
    image: 'codeclimate/codeclimate'
    volumes:
      - "./:/code"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/cc:/tmp/cc"
    # environment:
    # All calls with sudo would require -E to avoid warning
    #   - CODECLIMATE_CODE=${PWD}
    command: validate-config
    tty: true
    stdin_open: true

secrets:
  api-django-secret-key:
    file: ./unbrake-api/secrets/API_DJANGO_SECRET_KEY
  mqtt-reading-key:
    file: ./unbrake-api/secrets/MQTT_READING_KEY
  mqtt-writing-key:
    file: ./unbrake-api/secrets/MQTT_WRITING_KEY
