version: '3.7'

services:
  frontend:
    container_name: 'unbrake-frontend-development'
    build:
      context: ./unbrake-frontend
      dockerfile: Dockerfile
    image: unbrake_frontend_development
    volumes:
      - "./unbrake-frontend/src:/app/frontend/src"
      - "./unbrake-frontend/scripts:/app/frontend/scripts"
      - "./.git:/app/.git" # Needed for git hooks
    ports:
      - "3000:3000"
