# docker-compose for staging

version: '3.7'

services:
  proxy:
    volumes:
      - "./nginx.proxy.staging.conf:/etc/nginx/nginx.conf"
  api:
    image: 'unbrake/api:latest-staging'

  frontend:
    image: 'unbrake/frontend:latest-staging'
    volumes:
      - "./frontend/nginx.staging.conf:/etc/nginx/nginx.conf"

  api_server:
    volumes:
      - "./api/nginx.staging.conf:/etc/nginx/nginx.conf"
