# base configuration docker-compose file

version: '3.7'

services:
  api:
    image: 'unbrake/api:latest'
    depends_on:
      - db
    restart: unless-stopped
    secrets:
      - api-django-secret-key
      - postgres_password

  frontend:
    image: 'unbrake/frontend:latest'
    volumes:
      - "./logs/nginx:/var/log/nginx_frontend"
    restart: unless-stopped
    ports:
      - "80:80"

  db:
    image: 'postgres:11.2-alpine'
    container_name: 'api-database'
    environment:
      POSTGRES_PASSWORD_FILE: '/run/secrets/postgres_password'
      POSTGRES_DB: 'unbrake'
      POSTGRES_USER: 'unbrake'
      TZ: 'America/Sao_Paulo'
      PGTZ: 'America/Sao_Paulo'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    secrets:
      - postgres_password
    restart: unless-stopped

  api_server:
    image: 'nginx:1.15.12-alpine'
    container_name: 'api-server'
    volumes:
      - "./logs/nginx:/var/log/nginx_api"
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped

secrets:
  api-django-secret-key:
    file: secrets/API_DJANGO_SECRET_KEY
  postgres_password:
    file: secrets/DB_PASSWORD

volumes:
  postgres_data:
